name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        # SHA for v4.1.1
        # https://github.com/actions/checkout/releases/tag/v4.1.1
        # SHA: 2f0085d0ebd8372e912a6f1f8f6decc9c23d8573
        uses: actions/checkout@2f0085d0ebd8372e912a6f1f8f6decc9c23d8573

      - name: Setup Ruby
        # SHA for v1.170.0
        # https://github.com/ruby/setup-ruby/releases/tag/v1.170.0
        uses: ruby/setup-ruby@9b6c5a447e7b6e74cc8493c06f63e6b2b4a78698
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Setup Pages
        id: pages
        # SHA for v4.0.0
        # https://github.com/actions/configure-pages/releases/tag/v4.0.0
        uses: actions/configure-pages@12c8cdebfd7de76e282a68b8c23a1c342ccfc4d4

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        # SHA for v2.0.0
        # https://github.com/actions/upload-pages-artifact/releases/tag/v2.0.0
        uses: actions/upload-pages-artifact@b5cd8d68fe2dc3e5f44a8f317b72a89a4b7e58f2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # SHA for v4.0.4
        # https://github.com/actions/deploy-pages/releases/tag/v4.0.4
        uses: actions/deploy-pages@4e2816d0a0a309bd5e61dc9f8943de2799e09c34

